### ISSUE TITLE
tr 的状态显示不符合预期

### ISSUE THREAD

**Issue by cosven** [PingCAP-QE/Naglfar#113]
kv4 和 kv5 曾经用过，但现在两台机器实际都没有用到，但它显示是 ready 状态。
期望状态是 finish 或者其它
![image](https://user-images.githubusercontent.com/4962134/105974888-4fe47f80-60c9-11eb-8aba-f8855a38a99b.png)

**Comment by mahjonp** [comment]
Thanks for your feedback. 

IMO the testResource shouldn't bound with a testTopogogy, a testResource is more like a VM instance than a K8s pod, the user needs to request them by advance and cannot auto-scale at any time after the request was applied, their lifetime is usually longer than a topology.
